name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@v3.34
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_languages: yes
          plugin_languages_ignored: html, css, scss
          plugin_languages_skipped: |
            BonhyeonGu/webrtc_nvr
            BonhyeonGu/citygml-to-3dtiles
            BonhyeonGu/3dcityWebLab
          plugin_languages_indepth: yes
          commits_authoring: bonhyeon.gu@9bon.org, Bonhyeon Gu, BonhyeonGu
